---
title: "R Notebook"
output: html_notebook
---

### 1. Vectores y matrices

```{r}
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

students_vector <- c(student_1, student_2, student_3, student_4, student_5)

students_matrix <- matrix(students_vector, nrow = 5, byrow = TRUE)

print("1. students_matrix")
students_matrix
```
### 2. Nombrado de una matriz

```{r}
name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics", "Legal_age")

rownames(students_matrix) <- name_students
colnames(students_matrix) <- name_courses_legal_age

print("2. students_matrix")
students_matrix
```
### 3. rowSums, cbind

```{r}
students_matrix_columns = ncol(students_matrix)
students_matrix_no_legal_age = students_matrix[, -students_matrix_columns]
total_grade_student <- rowSums(students_matrix_no_legal_age)

result_students <- cbind(students_matrix, total_grade_student)

print("3. result_students")
result_students
```
### 4. Seleccionando elementos de una matriz

```{r}
selected_elements <- result_students[c(1, 3, 5), c(2, 4)]

print("4. selected_elements")
selected_elements
```
### 5. Data frames

```{r}
students_grades_df <- data.frame(result_students)

subset(students_grades_df, subset = Accounting > 80 & Legal_age == TRUE)

print("5. students_grades_df")
students_grades_df
```
### 6. Funciones, Condicionales y Bucles

```{r}
students_projection <- function() {
  result_students_columns <- ncol(result_students)
  result_students_columns_with_grades = result_students_columns - 2
  for(i in 1 : nrow(result_students)) {
    print(rownames(result_students)[i])
    for(j in 1 : result_students_columns_with_grades) {
      print(paste("  ", colnames(result_students)[j]))
      student_grade <- result_students[i, j]
      if (student_grade <= 45) {
        print("    Student in risk")
      } else if (student_grade > 45 & student_grade < 61) {
        print("    Student may be approved")
      } else {
        print("    Student approved")
      }
    }
  }
}

print("6. students_projection")
students_projection()
```
### 7. Data frames y lapply

```{r}
index_education <- function(grade) {
  return((1 + (grade / 100)) / 2)
}

all_students_grade <- students_grades_df[, 1:4]

print("7. lapply")
lapply(all_students_grade, index_education)
```
### 8. Math utilities

```{r}
score_mean <- colMeans(students_grades_df[, 1:4])

print("8. score_mean")
score_mean
```